# Generated by Django 4.1 on 2022-08-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_delete_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='writer',
        ),
    ]
